name: tom
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.1
  location: ^5.0.0
  group_list_view: ^1.1.1
  flutter_rating_bar: ^4.0.1
  mediaquery_sizer: ^1.1.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  geolocator: ^11.0.0
  geoflutterfire_plus: ^0.0.21
  uuid: ^4.4.0
  material_floating_search_bar_2: ^0.5.0
  flutter_easyloading: ^3.0.5
  lazy_load_indexed_stack: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
